CREATE TABLE USER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  PASSWORD VARCHAR(64)
);

CREATE TABLE BLOGPOST(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  HEADLINE VARCHAR(30) NOT NULL,
  BLOGPOST VARCHAR(300) NOT NULL,
--  DATE BIGINT NOT NULL
-- eller id fra customer
);
